// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cckzfjlvfwvfmrukzywv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNja3pmamx2Znd2Zm1ydWt6eXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTE4MzksImV4cCI6MjA2MTUyNzgzOX0.LrM0RnrVTgoOBhC_FGIIIylnSj2P_80WBxPNTu3tNRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);