// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfwybwbsuydmcxhsfbdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmd3lid2JzdXlkbWN4aHNmYmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDYyNDAsImV4cCI6MjA2MjQ4MjI0MH0.TN-3V8rsUWb0dRRxp1IbNmm2xI9cbvdYI4UbbZopZ2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);