
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cckzfjlvfwvfmrukzywv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNja3pmamx2Znd2Zm1ydWt6eXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTE4MzksImV4cCI6MjA2MTUyNzgzOX0.LrM0RnrVTgoOBhC_FGIIIylnSj2P_80WBxPNTu3tNRI";

// Create a Supabase client configured with appropriate auth settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export types
export type Tables = Database['public']['Tables'];
export type TablesInsert = {
  [TableName in keyof Database['public']['Tables']]: Database['public']['Tables'][TableName]['Insert']
};
export type TablesUpdate = {
  [TableName in keyof Database['public']['Tables']]: Database['public']['Tables'][TableName]['Update']
};

// Export enums for easier access
export type DemandStatus = Database['public']['Enums']['demand_status'];
export type TransactionAction = Database['public']['Enums']['transaction_action'];
export type UserRole = Database['public']['Enums']['user_role'];
